### PR TITLE
Updates for jemalloc 4.2

### PR DESCRIPTION
**Pull request by yahooguntu**
Most of these changes are for undocumented renames of mallctl namespaces.

### CODE REVIEW

**Comment by be9** [comment]
Thanks @yahooguntu!

**Comment by SamSaffron** [comment]
I am pretty sure this break 3.6.0 support though  :( 

The problem with that is that the current gem depends on ffi that is out of date so we need to rebuild the old gem with ffi restriction lifted to get a gem usable for debugging on 3.6.0

**Comment by be9** [comment]
@SamSaffron could you make a PR?

**Comment by SamSaffron** [comment]
I would love to but I am so time poor at the moment, putting this on my long term list but no promises as of when I can get to it :(

**Comment by mitch-birti-sp** [comment]
Yeah, this is most likely a breaking change for older versions of jemalloc. If there was a way to detect which version was being used this could be changed to support both versions.

**Pull request merged**
